### ISSUE TITLE
Make code follow PEP8 and Pylint style

### ISSUE THREAD

**Issue by rajkk1** [desireevl/quantum-game-theory#13]
As requested [here](https://github.com/Qiskit/qiskit-aqua/blob/master/CONTRIBUTING.md#style-guide)

**Comment by desireevl** [comment]
On top of this we need to comment our code. I'll have a start on this today

**Comment by desireevl** [comment]
Follows PEP8 and Pylint style in https://github.com/desireevl/quantum-game-theory/commit/f81e5dc0bec4a255f8c294e259b5542fb0c1cf36. Yet to add comments

**Comment by desireevl** [comment]
Done in https://github.com/desireevl/quantum-game-theory/commit/f81e5dc0bec4a255f8c294e259b5542fb0c1cf36 but should be done again before qiskit integration
