### ISSUE TITLE
Game player options

### ISSUE THREAD

**Issue by desireevl** [desireevl/quantum-game-theory#24]
- [x] Make minority game playable for 1-4 players
- [x] Make chicken game playable for 1-4 players
- [x] Check if Bos game is playable for N players
- [x] Check if prisoner game is playable for N players

**Comment by rajkk1** [comment]
I made the minority game multi-player (1 - infinite). The chicken game is I think technically not multiplayer but I made up some rules (basically if more than one person continues straight, they get -10 and everyone else remains 0). Feel free to change those if you would like! And the other 2 I think it's basically restricted to 2 players. I looked around but I couldn't see any sensible extensions. We can make them up though if you would like?
