### ISSUE TITLE
Upgrades to the GUI

### ISSUE THREAD

**Issue by rajkk1** [desireevl/quantum-game-theory#5]
Potential upgrades:
- different set games
- add screen showing payoff table and/or description of game
- static results page
- more gate options
- show strategy before results
- show results of repeated play

**Comment by desireevl** [comment]
I think I would like to do a complete overhaul of the GUI. It looks nice and was easy to create for a 24hr hackathon but if we want to add more features and make it more reliable/responsive I think we should turn it into a Web app. We could use React or Vue and a graphing library for the plot?

**Comment by rajkk1** [comment]
Oh yeah that sounds like a great idea! Let's chat about this... AFTER YOUR VACATION 😁😁 but yeah I'm totally down to let you lead the ui/ux part and happy to help in any way :)

**Comment by desireevl** [comment]
Per our chat (4/10), we will initially just be creating a basic interface. @GeorgeW95 and I will be investigating what tools to use and how the GUI should be set up for possible future integration with qiskit or just standalone
