### ISSUE TITLE
QIP Abstract Submission

### ISSUE THREAD

**Issue by rajkk1** [desireevl/quantum-game-theory#7]
The Quantum Information Processing (QIP) Conference abstracts are due 13 Oct
http://www.szpclab.com/qip2020#/submissions

**Comment by JansenZZ** [comment]
Tentative title and abstract for QIP poster submission:

Title: Game-theoretic perspectives for multi-generator quantum GANs

Abstract: ...

**Comment by rajkk1** [comment]
To get to an optimal GAN, one has to find the Nash equilibrium of the minimax game between the Discriminator and Generator. 

2 main concerns from my side:

1. The game theory creator that we have designed creates n x n games, which does not include minimax games 
2. The original QuGAN paper already proposes a quantum gradient descent method to try and obtain the minimax.
